### ISSUE TITLE
Deploy failed for Stable coins

### ISSUE THREAD

**Issue by minimin-zhu** [parrisma/distledge#34]
mzhu@LAPTOP-U69ESMAL:~/digital-garage/distledge$ yarn hardhat run --network localhost scripts/deploy/deploy.js
yarn run v1.22.19
warning ../../package.json: No license field
$ /home/mzhu/digital-garage/distledge/node_modules/.bin/hardhat run --network localhost scripts/deploy/deploy.js

========================================

 D E P L O Y  T E S T  C O N T R A C T S

========================================

old shared config deleted successfully

Account Addresses
Escrow Manager     : [0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266]
Stable Coin Issuer : [0x70997970C51812dc3A010C7d01b50e0d17dc79C8]
Data Vendor        : [0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC]
Option Seller      : [0x90F79bf6EB2c4f870365E785982E1f101E93b906]
Option Buyer       : [0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65]

Issue Stable Coins

Started

TypeError: erc20USDStableCoin.isoCcyCode is not a function
    at deployStableCoins (/home/mzhu/digital-garage/distledge/scripts/deploy/deployStableCoins.js:13:76)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (/home/mzhu/digital-garage/distledge/scripts/deploy/deploy.js:45:57)

Done

error Command failed with exit code 1.

**Comment by minimin-zhu** [comment]
deploy function changed to:
console.log(`Stable coin token for ISO Ccy [${await erc20USDStableCoin.**assetCode**()}] created at address [${erc20USDStableCoin.address}]`);

**Comment by minimin-zhu** [comment]
commit and push to the main done
