### ISSUE TITLE
Write tests for SimpleOption

### ISSUE THREAD

**Issue by parrisma** [parrisma/distledge#6]
There is only a stub test file at the moment, but there are examples it should work in Integration.js

**Comment by thatjamie** [comment]
Working on it, although still some dependency issue need to resolve... possibly due to my local setup, checking with team

`3 passing (2s)
  4 failing

  1) Financial Contract Full Integration Test and Simulation
       Integration Full Simulation
         Create Option to Trade:
     Error: cannot find artifact "MockV3Aggregator"
      at Object.getArtifact (node_modules/hardhat-deploy/src/DeploymentsManager.ts:207:17)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at getContractFactoryByName (node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:228:20)
      at Context.<anonymous> (test/Integration/Integration.js:217:32)`
